name: C/C++ CI

env:
  CTEST_NO_TESTS_ACTION: error
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/c-cpp.yml"

jobs:
  core:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        shared: [true, false]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: config shared=${{ matrix.shared }}
      run: >-
        cmake
        -Bbuild
        -DBUILD_SHARED_LIBS=${{ matrix.shared }}       
    - name: build
      run: cmake --build build --parallel
